version: '3.9'
services:
  backend:
    image: college-st-backend:latest
    environment:
      DJANGO_SECRET_KEY:
      SUPABASE_DB_USER:
      SUPABASE_DB_PASS:
      SUPABASE_DB_HOST:
      SUPABASE_DB_PORT:
      SUPABASE_DB_NAME:
      EMAIL_USER:
      EMAIL_PASSWORD:
    ports:
      - 8000:8000
    networks: 
      - app-test
    command: python manage.py runserver 0.0.0.0:8000
    build: 
      dockerfile: ./code/server/Dockerfile
  frontend:
    image: college-st-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://college-st-backend:8000/
    ports:
      - 3000:3000
    networks: 
      - app-test
    build: 
      dockerfile: ./code/web-app/Dockerfile
volumes:
  db:
    driver: local
networks:
    app-test:
        driver: bridge